### ISSUE TITLE
Get Error in Kodi with Dreamfilm for kodi

### ISSUE THREAD

**Issue by Rinsewood** [daniel-lundin/dreamfilm-xbmc#45]
Hello

I get error from whatever i choose in the plugin. All works on the webpage so it still exists.

**Comment by inkui** [comment]
Same. Pretty sure version in Kodi shown 0.1.16 but when I got to last release it shows 0.1.15. Weird. Most likely I remembered wrong though. Anyway, same problem. Nothing works. Scrip failed.

**Comment by Qualdrin** [comment]
Hi,
I managed to solve the problem. 
Seems url to dreamfilmhd has changed from .org to .sh.
Just edit the file dreamfilm.py and change the url. 
API_BASE_URL = 'http://www.dreamfilmhd.org/API/api.php' (change .org to .sh).
Works fine after that.

For Winodws 10 it is located in: C:\Users\"username"\AppData\Roaming\Kodi\addons\plugin.video.dreamfilm\dreamfilm.py

**Comment by inkui** [comment]
Hello again.
Ah, yeah. Nice. But... how do I do it on a Raspberry Pi? I changed the file in the rar as you said. Now I can't install it on Kodi. :<

**Comment by lillmorten** [comment]
**API_BASE_URL = 'http://www.dreamfilmhd.org/API/api.php' (change .org to .sh).**
Works Raspberry Pi Kodi but not working on Kodi Ubuntu desktop

**Comment by inkui** [comment]
No, not on Kodi either. I got the addon working until I played up a movie
or series. Tried quite a few. They all say "Cannot play >longlink<". Maybe
that's another problem though? I don't know this very well.

Regards,
Richard
Den 30 mars 2017 22:11 skrev "lillmorten" <notifications@github.com>:

*API_BASE_URL = 'http://www.dreamfilmhd.org/API/api.php
<http://www.dreamfilmhd.org/API/api.php>' (change .org to .sh).*
Works Raspberry Pi Kodi but not working on Kodi Ubuntu desktop

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/daniel-lundin/dreamfilm-xbmc/issues/45#issuecomment-290530439>,
or mute the thread

**Comment by telgetok** [comment]
anyone has a working dreamfilm addon now ?
i tried fixing files but i cant start videos :-/ .

**Comment by cabban** [comment]
no issue, the new is .info :) i tried , atm i had open 5 movies and tw show :) enjoy

**Comment by inkui** [comment]
Uhm... .info what? What should I do? :)

2017-10-29 8:10 GMT+01:00 cabban <notifications@github.com>:

**Comment by cabban** [comment]
Hej, den nya dreamfilm aressen e .info eftersom de andra har inte funkar och addon aldrig nästan, men nu funkar allt .:) när jag in i roaming och ändra källa till .info mvh

Fixa det så kommer det funka 😊 för det e ett jvla bra addon 😊 Med vänlig hälsning 
Skickades från E-post för Windows 10

Från: inkui
Skickat: den 29 oktober 2017 21:10
Till: daniel-lundin/dreamfilm-xbmc
Kopia: cabban; Comment
Ämne: Re: [daniel-lundin/dreamfilm-xbmc] Get Error in Kodi with Dreamfilmfor kodi (#45)

Uhm... .info what? What should I do? :)

2017-10-29 8:10 GMT+01:00 cabban <notifications@github.com>:

**Comment by kokangit** [comment]
Fixed earlier

**Comment by cabban** [comment]
no why closed. it worked but now again failed to open stream alles stream , :( so no its not fixed

**Comment by uk-julian** [comment]
I received email over christmas about fixing url, and since then nothing works. Was hoping issue may have been fixed, but tried today afer updating via the master zip  and  all im getting is " failed to open stream".

Note an update was done 10 days ago, but what did that achieve or fix, as appears it  didn't change the url as was commented on above?.  Is that going to be done. Im on 0.1.15.9  andbunablebto se any update to this.

Any help appreciated  and HNY

**Comment by kokangit** [comment]
@uk-julian please use latest release: v0.1.15.11.

**Comment by uk-julian** [comment]
Many thanks. Downloaded masterzip again, addon has  gone to 15.11 and working, or two films do so assume ok. Quick question, I had the masterzip downloaded and on my system, which thought would update as and when you did an update. Is this not correct? and for your addon should i just periodically do a master download when or if I encountervproblems of streams not playing?.

Again thanks for your earlier quick response and  alls well at present.

**Comment by kokangit** [comment]
It's better to use the repository from here: [xbmc-swe-repo](https://github.com/kokangit/xbmc-swe-repo/releases)
Uninstall your dreamfilm plugin. Install the repo from above. Use the repo to install dreamfilm plugin. After that, the plugin will be automatically be updated when there is a new release.

**Comment by uk-julian** [comment]
Many thanks. Was unaware you had  had put the addon within a  repository. Recall this was raised back in the day two/three years, glad to know you worked it all out. Fully ofay with repo"s so will download and hopefully will sort out my veiwing once and for all. Regards.

**Comment by uk-julian** [comment]
Regret to advise that after downlosding repository and updating the addon from repo, nothing nows plays. Films  two of which played yestrday  just say, " failed to open stream" whislt tv shows  along with "failed to open stream, also show following path
  " http://vkpass.com/token/bdrxwnlzfjpq/vklhash/Pw7ly8Mztzzw "
What that is telling me I havent a clue, but same for all tv shows.

 So now stuck again as deleted the masterfile update from yesterday, and downloading master file today isnt making the addon work as it did yesterday strangly,  as commented on this morning.

Any suggestions welcome. Regards

**Comment by uk-julian** [comment]
Regret to advise that after downloading repository and updating the addon from repo, nothing nows plays. Films  of which played yestrday just say, " failed to open stream " whislt tv shows along with " failed to open stream "  has this line also for any episode I try

"Http:// vkpass.com / token / bdrxwnlzfjpq / vklhash / Pw7ly8Mztzzw " 

What that is telling me I havent a clue.

So now stuck again as deleted the masterfile update from yesterday, and downloading file today isnt making the addon work as it did yesterday.  Any help appreciated as the addon was working with the master update, but not after repo update which i didnt need to do anyway, doh doh doh,. 

What do you think? Could it be related to the change as detailed above in the repo, but that doesn't explain why master download today doesnt work. Very confused now. Regards

**Comment by cabban** [comment]
latest release
![image](https://user-images.githubusercontent.com/19514493/35009210-2ee622c6-faff-11e7-8e65-b9e44867f226.png)

**Comment by cabban** [comment]
this i hope could be fixed almost ever movie is this message pops up on :( 
@kokangit

**Comment by uk-julian** [comment]
Have been trying various streams over the lastbfew days. As per Cabben posts, unable to get any film, and many have been tried to play. All say FTOS.  On the tv side getting mixed results. Am able to watch most seasons of the big bang theory no problems, even allows quality pick for stream.  Tried Prison break, nothing, all seasons FTOS  and then http.....etc., Narcos ditto,  Modern Family, ditto although some episodes try to play , but then fail.  See saeson 6, episode 7, pick 720 , tries ... fails. If you look at Varg Veum , by episode you can get all the variances of failure, from  FTOS, etc, and select quality faiure fails. Hopefully this may help with finding solution. It is most perculiar to my mind.

**Comment by cabban** [comment]
@uk-julian  first who is cabben:P cabban :) 

btw yes i hope its gonna get a fix for this annoying issue , write this post of your on the issue which is open, i think this is closed cheers m8

**Comment by uk-julian** [comment]
Oops sorry and Apologies on the name.

**Comment by kokangit** [comment]
Fixed!
